// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/ss.proto

package filesystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_proto_ss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_ss_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_proto_ss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_ss_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_ss_proto protoreflect.FileDescriptor

const file_proto_ss_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ss.proto\x12\x02pb\"2\n" +
	"\x0fSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\",\n" +
	"\x10SnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x89\x01\n" +
	"\x0fSnapshotService\x12=\n" +
	"\x10InitiateSnapshot\x12\x13.pb.SnapshotRequest\x1a\x14.pb.SnapshotResponse\x127\n" +
	"\n" +
	"SendMarker\x12\x13.pb.SnapshotRequest\x1a\x14.pb.SnapshotResponseB\x0eZ\f./filesystemb\x06proto3"

var (
	file_proto_ss_proto_rawDescOnce sync.Once
	file_proto_ss_proto_rawDescData []byte
)

func file_proto_ss_proto_rawDescGZIP() []byte {
	file_proto_ss_proto_rawDescOnce.Do(func() {
		file_proto_ss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ss_proto_rawDesc), len(file_proto_ss_proto_rawDesc)))
	})
	return file_proto_ss_proto_rawDescData
}

var file_proto_ss_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ss_proto_goTypes = []any{
	(*SnapshotRequest)(nil),  // 0: pb.SnapshotRequest
	(*SnapshotResponse)(nil), // 1: pb.SnapshotResponse
}
var file_proto_ss_proto_depIdxs = []int32{
	0, // 0: pb.SnapshotService.InitiateSnapshot:input_type -> pb.SnapshotRequest
	0, // 1: pb.SnapshotService.SendMarker:input_type -> pb.SnapshotRequest
	1, // 2: pb.SnapshotService.InitiateSnapshot:output_type -> pb.SnapshotResponse
	1, // 3: pb.SnapshotService.SendMarker:output_type -> pb.SnapshotResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ss_proto_init() }
func file_proto_ss_proto_init() {
	if File_proto_ss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ss_proto_rawDesc), len(file_proto_ss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ss_proto_goTypes,
		DependencyIndexes: file_proto_ss_proto_depIdxs,
		MessageInfos:      file_proto_ss_proto_msgTypes,
	}.Build()
	File_proto_ss_proto = out.File
	file_proto_ss_proto_goTypes = nil
	file_proto_ss_proto_depIdxs = nil
}
